### ISSUE TITLE
Does not work on a Raspberry 2

### ISSUE THREAD

**Issue by c64emulator** [sconemad/unicorn-scroller#1]
Have a Raspberry 2 with newest raspian-lite
- Installing PIL was a pain. Finally managed to work with `sudo apt-get install python-imaging`
- I had to give the files in the "messages"-path execute permission.
- The url of the rss-feeds in the weather-script seems to have changed

It still does not work. I'm stuck with the messages. They are not executed. process_message(path) throws errors.

**Comment by sconemad** [comment]
Hi,

Thanks for trying this! Looks like some things have changed with the new Raspbian Jessie release. I've had it running on a Pi 1 with Wheezy and basically not touched it since then. 

I've had a go at getting this working on a Pi 3 with Jessie, and had to do the following to get all the dependencies installed:

```
$ sudo apt-get install python-imaging
$ sudo pip install feedparser
$ sudo apt-get install python-dev
$ sudo pip install pyephem
$ sudo apt-get install fortune-mod
```

I'm not seeing the issue you describe with missing execute permissions. How are you getting the files onto your Pi? I did a git clone directly on the Pi itself, i.e.:
`$ git clone https://github.com/sconemad/unicorn-scroller.git`
And all the scripts appear to be executable as they should be. Are you doing the clone on another machine and copying it over, or downloading via a zip file? If so, that may not preserve the permissions. Still it should be easy to fix with chmod.

The weather feeds are working for me. You need to find the appropriate weather_id for your location, so it ends up with an URL like this:
http://open.live.bbc.co.uk/weather/feeds/en/2653941/observations.rss
...which works for me.

I know that some of the BBC pages are restricted to only work from the UK, so perhaps that's the reason? If so, you might need to look at an alternative source of weather data, and adapt the parsing code to work with the format it returns.

**Comment by c64emulator** [comment]
Hi,
after restarting from scratch, I finally managed to have a working unicorn scroller on a Pi0.

Downloading the zip-file was definitly the wrong way as permissions and links are missing than.

Thanks for support and sharing!

**Comment by sconemad** [comment]
Hi,
Thanks for letting me know. I'm glad you got it to work!
